import streamlit as st
import ollama
from openai import OpenAI
import requests
from typing import Optional, List, Dict, Any, Literal
from pydantic import BaseModel, ValidationError, Field
import time
import re  # Import the regular expression module
import json  # Add json import


class RequestStep(BaseModel):
    timestamp: float = Field(
        ..., description="Unix timestamp when the step was executed", ge=0
    )
    step_name: str = Field(..., description="Name of the processing step", min_length=1)
    model_used: str = Field(
        ..., description="Name/ID of the model used for this step", min_length=1
    )
    input_summary: str = Field(
        ..., description="Summary of the input provided to this step"
    )
    output_summary: str = Field(
        ..., description="Summary of the output generated by this step"
    )
    duration: float = Field(..., description="Duration of the step in seconds", ge=0)

    class Config:
        frozen = True  # Makes the model immutable
        validate_assignment = True  # Validates attribute assignments


class RequestTracker:
    def __init__(self):
        self.steps: List[RequestStep] = []
        self.start_time = time.time()

    def add_step(
        self,
        step_name: str,
        model_used: str,
        input_summary: str,
        output_summary: str,
    ):
        step_time = time.time()
        step = RequestStep(
            timestamp=step_time,
            step_name=step_name,
            model_used=model_used,
            input_summary=input_summary,
            output_summary=output_summary,
            duration=step_time - self.start_time,
        )
        self.steps.append(step)
        return step


# Models for request classification
class RequestType(BaseModel):
    type: Literal["ui_generation", "general_assistance"] = Field(
        ..., description="Type of the request being processed"
    )
    confidence: float = Field(
        ..., description="Confidence score of the classification", ge=0.0, le=1.0
    )
    requires_code: bool = Field(
        ..., description="Whether the request requires code generation"
    )
    description: str = Field(
        ..., description="Detailed description of the request type", min_length=1
    )
    suggested_model: str = Field(
        ..., description="Suggested model for handling this request type", min_length=1
    )

    class Config:
        frozen = True
        validate_assignment = True


class UIComponent(BaseModel):
    name: str = Field(
        ...,
        description="Name of the UI component",
        min_length=1,
        pattern="^[a-zA-Z][a-zA-Z0-9]*$",  # Valid component name pattern
    )
    type: Literal["react", "html", "svg"] = Field(
        ..., description="Type of UI component to generate"
    )
    description: str = Field(
        ...,
        description="Detailed description of the component's purpose and functionality",
        min_length=10,
    )
    complexity: Literal["low", "medium", "high"] = Field(
        ..., description="Estimated complexity level of the component"
    )

    class Config:
        frozen = True
        validate_assignment = True


class ModelCapabilities(BaseModel):
    classification: bool = Field(
        default=False, description="Whether the model supports request classification"
    )
    code_generation: bool = Field(
        default=False, description="Whether the model supports code generation"
    )
    ui_generation: bool = Field(
        default=False, description="Whether the model supports UI component generation"
    )
    analysis: bool = Field(
        default=False, description="Whether the model supports text analysis"
    )
    general_assistance: bool = Field(
        default=False, description="Whether the model supports general assistance tasks"
    )

    class Config:
        frozen = True


class ModelConfig(BaseModel):
    name: str = Field(..., description="Display name of the model", min_length=1)
    provider: Literal["ollama", "openrouter"] = Field(
        ..., description="Provider of the model"
    )
    model_id: str = Field(
        ..., description="Unique identifier for the model", min_length=1
    )
    capabilities: ModelCapabilities = Field(
        default_factory=ModelCapabilities, description="Capabilities of the model"
    )
    context_length: int = Field(
        default=4096, description="Maximum context length in tokens", gt=0
    )
    cost_per_1k_tokens: float = Field(
        default=0.0, description="Cost per 1000 tokens in USD", ge=0.0
    )
    description: str = Field(
        default="", description="Detailed description of the model"
    )
    family: str = Field(default="", description="Model family/architecture")
    parameter_size: str = Field(
        default="", description="Size of the model in parameters"
    )
    quantization_level: str = Field(
        default="", description="Level of model quantization"
    )

    class Config:
        frozen = True
        validate_assignment = True


def debug_model_fetching():
    """Display debug info in an expander."""
    with st.expander("🐛 Debug Information"):
        st.markdown("### Raw Ollama Response")
        try:
            raw_response = ollama.list()
            st.json(raw_response)
        except Exception as e:
            st.error(f"Failed to fetch Ollama models: {str(e)}")

        st.markdown("### Parsed Models (cached)")
        # Now fetch synchronously
        models_data = fetch_available_models()
        st.json(models_data)


@st.cache_data(ttl=300)
def fetch_available_models(openrouter_api_key: str = "") -> Dict[str, Dict[str, Any]]:
    """
    Fetch available models from both Ollama and OpenRouter.
    Pass the OpenRouter API key as an argument to force cache invalidation.
    """
    models_dict = {}

    # Fetch Ollama models
    try:
        response = ollama.list()
        if "models" in response:
            for model_data in response["models"]:
                model_name_match = re.search(r"model='(.*?)'", str(model_data))
                family_match = re.search(r"family='(.*?)'", str(model_data))
                parameter_size_match = re.search(
                    r"parameter_size='(.*?)'", str(model_data)
                )
                quantization_level_match = re.search(
                    r"quantization_level='(.*?)'", str(model_data)
                )

                model_name = (
                    model_name_match.group(1) if model_name_match else "unknown"
                )
                family = family_match.group(1) if family_match else "unknown"
                parameter_size = (
                    parameter_size_match.group(1) if parameter_size_match else "unknown"
                )
                quantization_level = (
                    quantization_level_match.group(1)
                    if quantization_level_match
                    else "unknown"
                )

                capabilities = {
                    "classification": True,
                    "code_generation": "B" in parameter_size
                    and float(parameter_size.replace("B", "").replace(" ", "")) >= 7.0,
                    "ui_generation": "B" in parameter_size
                    and float(parameter_size.replace("B", "").replace(" ", "")) >= 7.0,
                    "analysis": True,
                    "general_assistance": True,
                }
                # Granite special logic
                if "granite" in model_name.lower():
                    if "2b" in model_name.lower():
                        capabilities = {
                            "classification": True,
                            "code_generation": False,
                            "ui_generation": False,
                            "analysis": False,
                            "general_assistance": True,
                        }
                    elif "8b" in model_name.lower():
                        capabilities = {
                            "classification": False,
                            "code_generation": True,
                            "ui_generation": True,
                            "analysis": True,
                            "general_assistance": True,
                        }

                models_dict[f"ollama/{model_name}"] = {
                    "name": model_name,
                    "provider": "ollama",
                    "model_id": model_name,
                    "capabilities": capabilities,
                    "context_length": 32768,
                    "cost_per_1k_tokens": 0.0,  # Ollama models are free
                    "description": f"Family: {family}, Size: {parameter_size}, Quantization: {quantization_level}",
                    "family": family,
                    "parameter_size": parameter_size,
                    "quantization_level": quantization_level,
                }

    except requests.exceptions.ConnectionError as e:
        st.warning(f"Failed to connect to Ollama: {e}")
    except Exception as e:
        st.warning(f"Failed to fetch Ollama models: {e}")

    # Fetch OpenRouter models
    if openrouter_api_key:  # Use the passed-in key
        try:
            response = requests.get(
                "https://openrouter.ai/api/v1/models",
                headers={
                    "Authorization": f"Bearer {openrouter_api_key}",
                    "HTTP-Referer": "localhost:8501",
                    "X-Title": "Unified Chat Router",
                },
            )
            response.raise_for_status()
            data = response.json()
            # The OpenRouter API returns models in a 'data' key
            if isinstance(data, dict) and "data" in data:
                model_list = data["data"]
            else:
                model_list = (
                    data if isinstance(data, list) else []
                )  # Handle unexpected formats

            for model in model_list:
                model_id = model.get("id")
                if not model_id:
                    continue
                context_length = model.get("context_length", 4096)
                pricing = model.get("pricing", {})

                # Ensure cost is non-negative
                try:
                    cost = float(pricing.get("prompt", 0.0))
                    cost = max(0.0, cost)  # Ensure non-negative
                except (ValueError, TypeError):
                    cost = 0.0  # Default to free if invalid cost

                capabilities = {
                    "classification": True,
                    "code_generation": context_length >= 8192,
                    "ui_generation": context_length >= 8192,
                    "analysis": True,
                    "general_assistance": True,
                }

                # Get additional details if available, providing defaults
                family = model.get("family", "Unknown")
                parameter_size = model.get("parameter_size", "Unknown")
                quantization_level = model.get("quantization_level", "Unknown")

                models_dict[f"openrouter/{model_id}"] = {
                    "name": model.get("name", model_id),
                    "provider": "openrouter",
                    "model_id": model_id,
                    "capabilities": capabilities,
                    "context_length": context_length,
                    "cost_per_1k_tokens": cost,
                    "description": model.get("description", ""),
                    "family": family,
                    "parameter_size": parameter_size,
                    "quantization_level": quantization_level,
                }

        except requests.exceptions.RequestException as e:
            st.warning(f"Request to OpenRouter failed: {e}")
        except Exception as e:
            st.warning(f"Failed to fetch OpenRouter models: {e}")

    return models_dict


def initialize_state():
    """Initialize session state variables."""
    if "openrouter_api_key" not in st.session_state:
        st.session_state.openrouter_api_key = ""
    if "classification_model" not in st.session_state:
        st.session_state.classification_model = "ollama/granite3.1-dense:2b"
    if "generation_model" not in st.session_state:
        st.session_state.generation_model = "ollama/granite3.1-dense:8b"
    if "messages" not in st.session_state:
        st.session_state.messages = []


def get_model_client(model_config: ModelConfig):
    """Return appropriate client based on model provider."""
    if model_config.provider == "ollama":
        return ollama
    elif model_config.provider == "openrouter":
        if not st.session_state.openrouter_api_key:
            raise ValueError("OpenRouter API key is required for OpenRouter models")
        return OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=st.session_state.openrouter_api_key,
            default_headers={
                "HTTP-Referer": "localhost:8501",  # Replace with your actual referrer
                "X-Title": "Unified Chat Router",
            },
        )
    else:
        raise ValueError(f"Unknown provider: {model_config.provider}")


def display_response_with_timeline(response: Dict[str, Any]):
    """Display the response along with a timeline of steps."""
    if response["type"] == "error":
        st.error(response["response"])
        return

    st.info(f"Request Type: {response['type']}")
    st.caption(f"Final Model Used: {response['model_used']}")

    st.markdown("### 📊 Request Timeline")
    for step in response["request_timeline"]:
        col1, col2 = st.columns([3, 1])
        with col1:
            st.markdown(f"**{step['step_name']}**")
        with col2:
            st.markdown(f"_{step['duration']:.2f}s_")
        st.markdown(f"Model: `{step['model_used']}`")
        st.markdown("**Input:**")
        st.code(step["input_summary"])
        st.markdown("**Output:**")
        st.code(step["output_summary"])
        st.markdown("---")

    st.markdown("### 💬 Response")
    if response["type"] == "ui_generation":
        with st.expander("Component Details"):
            st.json(response["component_details"])
        st.code(response["response"])
    else:
        st.write(response["response"])


def display_model_selector(models: Dict[str, ModelConfig]):
    """Display the model selection UI in the sidebar."""
    st.sidebar.markdown("### 🔧 Model Settings")

    st.sidebar.text_input(
        "OpenRouter API Key",
        type="password",
        key="openrouter_api_key",
        help="Required for using OpenRouter models",
    )

    providers = ["All"] + sorted(list(set(m.provider for m in models.values())))
    selected_provider = st.sidebar.selectbox(
        "Filter by Provider", options=providers, help="Filter models by provider"
    )

    if selected_provider == "All":
        filtered_models = models
    else:
        filtered_models = {
            k: v for k, v in models.items() if v.provider == selected_provider
        }

    st.sidebar.markdown("#### Classification Model")
    classification_models = {
        k: v for k, v in filtered_models.items() if v.capabilities.classification
    }

    if classification_models:
        # Get the current model from session state or use the first available model
        current_classification_model = st.session_state.get("classification_model")
        if (
            not current_classification_model
            or current_classification_model not in classification_models
        ):
            # Set default to first available model if current is not available
            st.session_state.classification_model = next(iter(classification_models))

        selected_model = st.sidebar.selectbox(
            "Select Classification Model",
            options=list(classification_models.keys()),
            format_func=lambda x: classification_models[x].name,
            key="classification_model",
            help="Model used for initial request classification",
        )
        if selected_model in models:
            model = models[selected_model]
            st.sidebar.markdown(
                f"""
**Model Details:**
- Provider: {model.provider}
- Context Length: {model.context_length:,}
- Cost per 1k tokens: ${model.cost_per_1k_tokens:.4f}
- Family: {model.family}
- Size: {model.parameter_size}
"""
            )
            if model.description:
                with st.sidebar.expander("Model Description"):
                    st.markdown(model.description)
    else:
        st.sidebar.warning("No classification models available")

    st.sidebar.markdown("#### Generation Model")
    generation_models = {
        k: v for k, v in filtered_models.items() if v.capabilities.code_generation
    }

    if generation_models:
        # Get the current model from session state or use the first available model
        current_generation_model = st.session_state.get("generation_model")
        if (
            not current_generation_model
            or current_generation_model not in generation_models
        ):
            # Set default to first available model if current is not available
            st.session_state.generation_model = next(iter(generation_models))

        selected_model = st.sidebar.selectbox(
            "Select Generation Model",
            options=list(generation_models.keys()),
            format_func=lambda x: generation_models[x].name,
            key="generation_model",
            help="Model used for code and UI generation",
        )
        if selected_model in models:
            model = models[selected_model]
            st.sidebar.markdown(
                f"""
**Model Details:**
- Provider: {model.provider}
- Context Length: {model.context_length:,}
- Cost per 1k tokens: ${model.cost_per_1k_tokens:.4f}
- Family: {model.family}
- Size: {model.parameter_size}
"""
            )
            if model.description:
                with st.sidebar.expander("Model Description"):
                    st.markdown(model.description)
    else:
        st.sidebar.warning("No generation models available")

    st.sidebar.markdown("---")
    st.sidebar.markdown("### 📊 Available Models")
    total_models = len(models)
    ollama_count = sum(1 for m in models.values() if m.provider == "ollama")
    openrouter_count = sum(1 for m in models.values() if m.provider == "openrouter")
    st.sidebar.markdown(
        f"""
- Total: {total_models} models
- Ollama: {ollama_count} models
- OpenRouter: {openrouter_count} models
"""
    )

    if st.sidebar.button("🔄 Refresh Models"):
        st.cache_data.clear()
        st.rerun()


def route_request(prompt: str, models: Dict[str, ModelConfig]) -> Dict[str, Any]:
    """Route the user's request to the appropriate handler."""
    tracker = RequestTracker()

    try:
        classification_model = models[st.session_state.classification_model]
        classification_client = get_model_client(classification_model)

        system_prompt = """You are a router system that analyzes requests and determines their type.
Return a JSON object with:
- type: either "ui_generation" or "general_assistance"
- confidence: a float between 0.0 and 1.0 (not percentage)
- requires_code: boolean
- description: string describing the request
- suggested_model: string with model name

Example response:
{
    "type": "general_assistance",
    "confidence": 0.95,
    "requires_code": false,
    "description": "General question about programming",
    "suggested_model": "gpt-3.5-turbo"
}"""

        if classification_model.provider == "ollama":
            classification = classification_client.chat(
                model=classification_model.model_id,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                format=RequestType.model_json_schema(),
                options={"temperature": 0},
            )
            response_content = classification.message.content
        else:
            classification = classification_client.chat.completions.create(
                model=classification_model.model_id,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0,
            )
            response_content = classification.choices[0].message.content

        # Parse the response and ensure confidence is a float between 0 and 1
        response_dict = (
            response_content
            if isinstance(response_content, dict)
            else json.loads(response_content)
        )

        # Convert confidence to float and normalize if it's a percentage
        confidence = float(response_dict["confidence"])
        if confidence > 1:  # If confidence is given as percentage
            confidence = confidence / 100.0
        response_dict["confidence"] = confidence

        request_type = RequestType.model_validate(response_dict)

        tracker.add_step(
            "Classification",
            st.session_state.classification_model,
            f"User prompt: {prompt[:100]}...",
            f"Classification: {request_type.model_dump_json()}",
        )

        generation_model = models[st.session_state.generation_model]
        generation_client = get_model_client(generation_model)

        if request_type.type == "ui_generation":
            component_prompt = """You are using the {model} model to generate UI components...
[Your existing component prompt here]"""  # Removed extra line breaks

            if generation_model.provider == "ollama":
                details_response = generation_client.chat(
                    model=generation_model.model_id,
                    messages=[
                        {"role": "system", "content": component_prompt},
                        {"role": "user", "content": prompt},
                    ],
                    format=UIComponent.model_json_schema(),
                )
                component_details = details_response.message.content
            else:
                details_response = generation_client.chat.completions.create(
                    model=generation_model.model_id,
                    messages=[
                        {"role": "system", "content": component_prompt},
                        {"role": "user", "content": prompt},
                    ],
                    response_format={"type": "json_object"},
                )
                component_details = details_response.choices[0].message.content

            tracker.add_step(
                "Component Analysis",
                st.session_state.generation_model,
                f"Analyzing component requirements for: {prompt[:100]}...",
                f"Component details: {component_details}",
            )

            code_prompt = f"""Generate a complete, working React component that fulfills these requirements:

{prompt}

The component should:
1. Include all necessary imports
2. Use modern React practices (hooks, functional components)
3. Include proper TypeScript/PropTypes if needed
4. Include basic styling
5. Be well-commented
6. Be production-ready

Return only the component code without any explanations."""

            if generation_model.provider == "ollama":
                code_response = generation_client.chat(
                    model=generation_model.model_id,
                    messages=[
                        {
                            "role": "system",
                            "content": "You are an expert React developer. Generate complete, working component code.",
                        },
                        {"role": "user", "content": code_prompt},
                    ],
                )
                generated_code = code_response.message.content
            else:
                code_response = generation_client.chat.completions.create(
                    model=generation_model.model_id,
                    messages=[
                        {
                            "role": "system",
                            "content": "You are an expert React developer. Generate complete, working component code.",
                        },
                        {"role": "user", "content": code_prompt},
                    ],
                )
                generated_code = code_response.choices[0].message.content

            tracker.add_step(
                "Code Generation",
                st.session_state.generation_model,
                "Generating component code...",
                f"Generated code length: {len(generated_code)} characters",
            )

            return {
                "type": "ui_generation",
                "model_used": st.session_state.generation_model,
                "response": generated_code,
                "classification_details": request_type.model_dump(),
                "component_details": component_details,
                "request_timeline": [step.model_dump() for step in tracker.steps],
            }
        else:
            if generation_model.provider == "ollama":
                response = generation_client.chat(
                    model=generation_model.model_id,
                    messages=[{"role": "user", "content": prompt}],
                )
                response_content = response.message.content
            else:
                response = generation_client.chat.completions.create(
                    model=generation_model.model_id,
                    messages=[{"role": "user", "content": prompt}],
                )
                response_content = response.choices[0].message.content

            tracker.add_step(
                "General Response",
                st.session_state.generation_model,
                prompt,
                response_content,
            )

            return {
                "type": "general_assistance",
                "model_used": st.session_state.generation_model,
                "response": response_content,
                "classification_details": request_type.model_dump(),
                "request_timeline": [step.model_dump() for step in tracker.steps],
            }

    except Exception as e:
        tracker.add_step("Error", "N/A", prompt, str(e))
        return {
            "type": "error",
            "error": str(e),
            "response": f"An error occurred: {str(e)}",
            "request_timeline": [step.model_dump() for step in tracker.steps],
        }


def main():
    st.set_page_config(page_title="Unified Chat Router", page_icon="🤖", layout="wide")

    initialize_state()

    st.title("🤖 Unified Chat Router")
    if st.sidebar.checkbox("Show Debug Info"):
        debug_model_fetching()

    # Crucial change: Pass the API key to fetch_available_models
    models_data = fetch_available_models(st.session_state.openrouter_api_key)
    models: Dict[str, ModelConfig] = {
        k: ModelConfig(**v) for k, v in models_data.items()
    }

    display_model_selector(models)

    if st.sidebar.button("🗑️ Clear Chat History"):
        st.session_state.messages = []
        st.rerun()  # Force a re-render

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            if message["role"] == "user":
                st.write(message["content"])
            else:
                display_response_with_timeline(message["content"])

    if prompt := st.chat_input("What would you like me to help you with?"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                response = route_request(prompt, models)
                st.session_state.messages.append(
                    {"role": "assistant", "content": response}
                )
                display_response_with_timeline(response)


if __name__ == "__main__":
    main()