/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      backgroundColor: {
        'success-focus': '#16a34a', // Replace with your desired color
      },
      colors: {
        'primary': '#007bff',
        'muted': 'hsl(var(--muted))',
        'border': 'hsl(var(--border))',
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        dark: {
          "primary": "#3b82f6",
          "secondary": "#14b8a6",
          "accent": "#a855f7",
          "neutral": "#1f2937",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          "base-content": "#f9fafb",
          "info": "#3b82f6",
          "success": "#22c55e",
          "warning": "#facc15",
          "error": "#ef4444",
        },
        dracula: {
          "primary": "#FF3333",
          "secondary": "#FFFFFF",
          "accent": "#000000",
          "neutral": "#000000",
          "base-100": "#000000",
          "base-200": "#0a0a0a",
          "base-300": "#141414",
          "base-content": "#FFFFFF",
          "info": "#FF3333",
          "success": "#22c55e",
          "warning": "#facc15",
          "error": "#ef4444",
        },
        neon: {
          "primary": "#FF79C6",
          "secondary": "#BD93F9",
          "accent": "#50FA7B",
          "neutral": "#1a1a2e",
          "base-100": "#16213e",
          "base-200": "#1a1a2e",
          "base-300": "#0f3460",
          "base-content": "#FFFFFF",
          "info": "#8be9fd",
          "success": "#50fa7b",
          "warning": "#f1fa8c",
          "error": "#ff5555",
        },
      },
      "light",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
}